// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XtremeK {
	
	
	public partial class Home {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected Telerik.Web.UI.RadScriptManager scriptManager;
		
		protected System.Web.UI.WebControls.ImageButton logo;
		
		protected System.Web.UI.WebControls.ImageButton emailButton;
		
		protected System.Web.UI.WebControls.ImageButton printButton;
		
		protected System.Web.UI.WebControls.ImageButton refreshButton;
		
		protected System.Web.UI.WebControls.ImageButton tagButton;
		
		protected Telerik.Web.UI.RadToolTipManager RadToolTipManager1;
		
		protected System.Web.UI.WebControls.ImageButton unitsButton;
		
		protected System.Web.UI.WebControls.ImageButton adminButton;
		
		protected System.Web.UI.WebControls.ImageButton reportsButton;
	}
}
